### ISSUE TITLE
Breaks the latest version of Atom

### ISSUE THREAD

**Issue by bdeweygit** [jovrtn/tron-green-ui#6]
Atom: 1.37.0
OS: macOS Mojave 10.14.5

Steps to reproduce

1. Install the latest version of Atom (currently 1.37.0)
2. Go to Settings -> Install
3. Install `tron-green-ui`
4. Go to Settings -> Themes
5. Select `Tron Green` as the UI Theme
6. Close Atom
7. Try doing anything with Atom; it will only display a blank gray screen

**Comment by bdeweygit** [comment]
#7 should fix this

**Comment by jovrtn** [comment]
@Benjamin-Dewey Merged! Appreciate the help.
